### ISSUE TITLE
add users to mbon server

### ISSUE THREAD

**Issue by bbest** [marinebon/sdg14#12]
Keeping track of users here:
- [Github & mbon.marine.usf.edu accounts - Google Sheets](https://docs.google.com/spreadsheets/d/1KEH0dyjQemg_Tfik0dIIyQ30cqQ1eRcWTaMuZwUO49U/edit#gid=0)

From Qiao (@asurinsaka): 
- Dan has the id 510
- Enrique has id 29914
- Megan Hepner has the id 528

```bash
# determine user id
id -u `whoami`
```

## Add user

To both server `mbon.marine.usf.edu` and RStudio docker container for access to RStudio IDE at http://mbon.marine.usf.edu:8787:

References:
- get password(s) from [RANDOM.ORG - Password Generator](https://www.random.org/passwords/)
- [AddUsersHowto - Community Help Wiki](https://help.ubuntu.com/community/AddUsersHowto)
- [Ubuntu Manpage: adduser, addgroup - add a user or group to the system](http://manpages.ubuntu.com/manpages/precise/man8/adduser.8.html)
- docker notes: https://github.com/marinebon/sdg14/issues/4#issuecomment-288746359

```bash
# add user to server
sudo adduser <user>
# OR for a specific userid
sudo adduser --uid <userid> <user> 
# add user to group users
sudo adduser <user> users

# add user to RStudio container
docker ps    # confirm containerid
containerid=fa81e7ac1b2d
docker exec -it $containerid bash
adduser <user>
# OR for a specific userid
adduser --uid <userid> <user> 
# add user to group users
adduser <user> users 
```

**Comment by bbest** [comment]
Added users:
- ben
- dotis
- mkavanaugh
- closek

**Comment by bbest** [comment]
Added users:
- druedaro:29898:Digna Rueda-Roa
- qiao:534:Qiao Qiao
- tylarmurray:538: Tylar Murray

## Enabling RStudio for Low UserID

In order to enable users with ids < 1000, had to update [3.2.1 Minimum User Id - RStudio Server Professional Edition](http://docs.rstudio.com/ide/server-pro/authenticating-users.html#restricting-access-to-specific-users) in `/etc/rstudio/rserver.conf`:

```
auth-minimum-user-id=100
```

Then:

```bash
 sudo rstudio-server restart
```

**Comment by bbest** [comment]
## Change password

### server mbon.marine.usf.edu

Log into the terminal from your machine

```bash
# change to your user name!
user=ben

# secure shell onto the machine
ssh  $user@mbon.marine.usf.edu
```

Change password on server mbon.marine.usf.edu, for access to files and shell.

```bash
# change passwd
passwd
```

### Rstudio docker container

Change password in the RStudio docker container for logging into http://mbon.marine.usf.edu:8787

```bash
# confirm containerid
docker ps    
containerid=304b27b9411c

# change to your user name!
user=ben

# log into terminal in the RStudio docker 
docker exec --user $user -it $containerid bash

# change passwd
passwd
```

**Comment by bbest** [comment]
From @7yl4r:

## So here is the issue:

Ben's groups exist only on the mbon server, so they don't work on seashell. This is also true for usernames, but so long as the uid numbers match it will work (which is why those have been configured manually to match).

## Quick fix:

Manually align groups across mbon & seashell (via LDAP).

Unfortunately the group id "100" (mbon server "users" group gid) is already being used in our LDAP configuration, so I have created a new group with gid 528 for the mbon project and added relevant users. 

Ben: you will need to change the id of the "users" group on mbon to match 528 or create a new group with this id because I do not have sudo access (if you prefer I do this you will need to grant me sudo access). Once this is done we will be able to use this group across imars servers & mbon

![image](https://cloud.githubusercontent.com/assets/2837257/26600886/9c5091bc-4532-11e7-9f48-30f8592298f6.png)

## Better (but possibly harder) fix:
We could set up mbon to work with our LDAP server. This is something I have not done yet, but will be working on soon for another server anyway. Ben: if you are comfortable with LDAP and want to go this route that's fine by me.

~Tylar

----
Hi @7yl4r,

Here's what I did on mbon:

## Fix group users from GID 100 to 528

 [How to change user GID and UID in Ubuntu 13.04? - Ask Ubuntu](https://askubuntu.com/questions/312919/how-to-change-user-gid-and-uid-in-ubuntu-13-04):

```bash
sudo groupmod -g 528 users
sudo find / -group 100 -exec chgrp -h 528 {} \;
```

## Add Tylar to sudo group

```bash
sudo usermod -aG sudo tylarmurray
```

**Comment by 7yl4r** [comment]
There are a few files in /mbon/ which are in group 1000 instead of 528. Do you know if this is intentional or should I `chgrp -R mbon /mbon/`?

**Comment by bbest** [comment]
Hi @7yl4r, yes please fix group from 1000 (ben) to to 528 (users). Thank you 👍

**Comment by 7yl4r** [comment]
done! 

`chgrp -R 528 /mbon/` ran & looks good from seashell.

**Comment by bbest** [comment]
Great, thanks Tylar!
