### ISSUE TITLE
postgis docker at cpu max, not finishing query, needs more VM resource

### ISSUE THREAD

**Issue by bbest** [marinebon/sdg14#20]
Hi @7yl4r,

The query to determine EEZ polygon for OBIS points (n= 43,140,428) has been running for almost 24 hours now, which seems insanely long for simple point in polygon operation on geographies already indexed:

```sql
SELECT o.gid AS obis_gid, e.gid AS eez_gid
 INTO obis_attr
 FROM obis_occ AS o LEFT JOIN eez AS e ON ST_Intersects(o.geog, e.geog);
 CREATE INDEX idx_obis_attr_obis ON obis_attr ("obis_gid");
 CREATE INDEX idx_obis_attr_eez  ON obis_attr ("eez_gid");
```

I saw the CPU maxxing out in the Docker postgis container:

```bash
ssh ben@mbon.marine.usf.edu
docker exec -it postgis bash
ps -eaf | grep psql
top
```

Now it appears calm although query still running and logging into RStudio (http://mbon.marine.usf.edu:8787/) taking an unreasonable amount of time

Of the options you proposed, I'd rather expand the existing VM rather than adding a new one, simply because I would have to transfer the database files to the new server and setup networking to allow external connections on the new postgis container. Feel free to shut it down whenever you like. I'll save as I go if I'm on and will let you know if doing anything critical. Thanks a bunch!

**Comment by 7yl4r** [comment]
`shutdown -h now`, added ram & cpus with virt-manager, restart and:

![image](https://user-images.githubusercontent.com/1051390/27546547-9cb422f8-5a82-11e7-93f5-10ef779f5e38.png)


Oh... it's going to be one of those Mondays.

I don't have a backup of this image but I am hoping it will only take some minor configuration change to get this running again.

**Comment by 7yl4r** [comment]
[Here's a gist](https://gist.github.com/7yl4r/ac623860ec868ad84efddba733ffe3e6/revisions) to track my configuration changes from here on. Suggestions welcomed. :sweat:

**Comment by bbest** [comment]
Doh! "No bootable device" -- not a fun message to see. Hmmm... I wonder if I mucked anything up when I formatted that extra partition for `/mbon/postgres`?

Please don't worry about needing to restore the docker boot instance from before. The important data were in the `/mbon` and `/mbon-postgres` mount points, which shouldn't have been the bootable device. The beauty of docker is that we can quickly install and launch the whole software stack.

I should be able to get going again if you can get me back to being able to :

- ssh into `mbon.marine.usf.edu` (username bbest preferable to former ben)
- having mount points `/mbon` and `/mbon/postgres` like before (#4)
- docker installed (or easy enough for me to do based on [Installation on Ubuntu](http://docs.master.dockerproject.org/engine/installation/linux/ubuntulinux/))

Please feel free to call me (805-705-9770) if I can help at all. Thanks a bunch @7yl4r!

**Comment by 7yl4r** [comment]
I have run out of ideas as far as libvirt configuration changes go. I was able to revert to a snapshot from 04-05 and this boots fine. Worst case scenario we can re-build starting from that point.

**Comment by 7yl4r** [comment]
I've managed to upgrade the ram & cpu on the older snapshot with no issues. 

I've also added the data volume to the vm. I don't have sudo in this older image so I can't mount it, but it should be easier than before since it is already partitioned & ready to go. 

As for `/mbon`: it looks like it was set up prior to this snapshot.

The only other thing I remember since then might be to re-align the uids/gids again.

@bbest : If you can log in and grant me sudo really quick again I will set up /mbon/postgres and double check the uids.

**Comment by bbest** [comment]
Hi @7yl4r,

That's great news! Ok, you should have sudo permissions:

```bash
sudo usermod -aG sudo tylarmurray
```

Thanks for getting this going!

**Comment by 7yl4r** [comment]
`/mbon-postgres` mounted & set to mount on boot. gid fix from #12 re-applied. 

All seems fine but I'd like to confirm it can come back from a reboot with this configuration before closing this. If you're feeling lucky give it a shot, else I'll check back and snapshot then reboot when it's not in use.

**Comment by bbest** [comment]
Hi @7yl4r,

Ok, I've logged in and see the old docker containers. No need to snapshot until I finish with redo.

```bash
ben@mbon:/$ docker container ls -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
fa81e7ac1b2d        rocker/geospatial   "/init"                  3 months ago        Exited (0) 2 months ago                         epic_easley
78ed762fd282        rocker/geospatial   "/init"                  3 months ago        Created                                         wonderful_wing
89e158638975        rocker/geospatial   "/init"                  3 months ago        Exited (137) 3 months ago                       nervous_edison
1d05bea0ec00        rocker/geospatial   "/init"                  3 months ago        Exited (137) 3 months ago                       agitated_jennings
ada522758d87        nginx               "nginx -g 'daemon ..."   4 months ago        Exited (0) 4 months ago                         docker-nginx
```

Will update ya when back up with newest docker configuration that'll have autorestart, so should also start on reboot.

**Comment by 7yl4r** [comment]
let me know before we try a restart but after you're done setting back up and I'll take a snapshot as a fallback.

Ironically my number one TODO this week was to improve our backups... Too bad I didn't get to that just one week earlier.
