### ISSUE TITLE
can't log in to rstudio

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/sdg14#23]
I had some spare time today and wanted to (finally) log into rstudio and poke around a bit, but found that I couldn't get in.

![image](https://user-images.githubusercontent.com/1051390/28723734-373f8136-73a7-11e7-8295-0d704ffe441a.png)

I poked around a bit on the server to see if I could troubleshoot it, but had no luck. Is Rstudio running on the VM directly or within one of the docker containers? Maybe within rstudio-shiny... but I thought the shiny container was separate? 

```
tylarmurray@mbon:~$ sudo docker container list 
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                            NAMES
4b5303165a56        bdbest/rstudio-shiny:R-3.4-geospatial   "/init"                  3 days ago          Up 3 days           0.0.0.0:3838->3838/tcp, 0.0.0.0:8787->8787/tcp   rstudio-shiny
5c54dfebd408        nginx                                   "nginx -g 'daemon ..."   2 weeks ago         Up 6 days           0.0.0.0:80->80/tcp                               www
719e5ca7cd7b        kartoza/geoserver                       "catalina.sh run"        2 weeks ago         Up 6 days           0.0.0.0:8080->8080/tcp                           geoserver
426f948c56b3        kartoza/postgis                         "/bin/sh -c /start..."   2 weeks ago         Up 6 days           0.0.0.0:5432->5432/tcp                           postgis
```

**Comment by bbest** [comment]
Hi Tyler,

I manually added users to mbon and the rstudio-shiny (yes, now combined so geospatial libraries available to shiny) so got wiped when reinstalled docker. Trying to use [`newusers`](http://manpages.ubuntu.com/manpages/trusty/man8/newusers.8.html) to create update easily.

Related issues:
- #12
- #4

**Comment by 7yl4r** [comment]
It's a bit verbose, but I guess you could do it manually for the users you want right? 

```bash
mkdir migrate_usr
cd migrate_usr
for usr in ('tylarmurray' 'otheruser' 'otherotheruser') do 
    grep $usr /etc/passwd >> passwd
    grep $usr /etc/group >> group
    grep $usr /etc/shadow >> shadow
    grep $usr /etc/gshadow >> gshadow
done
```

then move it to the container `scp migrate_usr ben@docker_container:.`, make back ups just in case and then append stuff in the container

```bash
mkdir newsusers.bak
cp /etc/passwd /etc/shadow /etc/group /etc/gshadow newsusers.bak

cd migrate_usr
cat passwd >> /etc/passwd
cat group >> /etc/group
cat shadow >> /etc/shadow
cat gshadow >> /etc/gshadow
```

Or do you want logins to be synced across the docker host and container? I might be able to hook mbon and the shiny container into our LDAP server, but maybe that is overkill on this.

**Comment by bbest** [comment]
Hi Tylar,

Thanks for these! I don't follow `scp migrate_usr ben@docker_container:.`. Since the `/mbon` volume is shared by the server mbon and all the docker containers, I just used the same R script to iterate through a `users.txt` file to use with `newusers`, which you can see at `/mbon/admin/add_users.R` and run with:

```bash
sudo Rscript /mbon/admin/add_users.R; cat /etc/passwd
``` 

Because of [Bug #1266675 “newusers error adding more than one user” : shadow package : Ubuntu](https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/1266675), I had to iterate per user but could at least feed the password without prompting.

You should be able to login again to http://mbon.marine.usf.edu:8787 as `tylarmurray`

**Comment by 7yl4r** [comment]
Nice! Docker is still a bit mysterious to me.

I'll test this out Monday. Thanks!

**Comment by 7yl4r** [comment]
hmm. Can't log into rstudio 

![image](https://user-images.githubusercontent.com/1051390/28780156-48f38daa-75f5-11e7-91d4-24dfc4109cd9.png)

...but... also can't ssh into the mbon server anymore

```
me@local:~$ ssh tylarmurray@mbon
tylarmurray@mbon's password: 
Permission denied, please try again.
```

**Comment by bbest** [comment]
Hi @7yl4r,

Just sent you the password I used for your account on both mbon server and rstudio-shiny docker.

**Comment by 7yl4r** [comment]
thanks! :+1:
