### ISSUE TITLE
where does the infographic controller code live?

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/sdg14#26]
I have worked with svg shapes made in inkscape and d3.js to manipulate them. It looks to me like this project's interactive infographic views are doing something similar.

I would like to take a look and see if I can help out on this aspect, but I'm not seeing the files I expected. Perhaps I'm misunderstanding how you're accomplishing the interactive-infographic effect.

**Comment by bbest** [comment]
Great! Check out https://marinebon.github.io/cr-metrics/README.html

**Comment by bbest** [comment]
The next step is to wire the latest FKNMS infographics and data:

- infographics:
   - image preview: [Florida Keys Infographic Art](http://mbon.marine.usf.edu/info-fk.html)
  - Adobe Illustrator (*.ai) files: [FKNMS Infographics - Google Drive](https://drive.google.com/drive/u/0/folders/0B4I0u8PRaP7IcW1tMEwwcGFUTUU)
- data:
  - [RVC/SDG14 at master · mhepner90/RVC](https://github.com/mhepner90/RVC/tree/master/SDG14)

**Comment by 7yl4r** [comment]
That README is very helpful. I'll see if I can help setting up the FKNMS stuff.
