### ISSUE TITLE
conceptualize initial SDG14 products: wireframe interfaces and draw use case diagrams

### ISSUE THREAD

**Issue by bbest** [marinebon/sdg14#3]
[Wireframe](https://webdesign.tutsplus.com/articles/a-beginners-guide-to-wireframing--webdesign-7399) user interfaces and [use case diagrams](http://www.uml-diagrams.org/index-examples.html) in free app [Pencil Project](http://pencil.evolus.vn/Default.html) for the following initial SDG14 products:

1. **Global infographic**
  ![image](https://cloud.githubusercontent.com/assets/2837257/24107083/36fa3a0c-0d60-11e7-9541-dbc8797365ae.png)
    - b. **MBNMS**: local level uses different datasets, perhaps different indices, so hard to 
    - c. **FKNMS**: local level uses different datasets, perhaps different indices, so hard to 
    - d. **eDNA** global ocean sampling day along coast. TARA expedition doing this oceanic, microbial focus (+ Arctic, Antarctica). Craig Ventner did this first.

1. **Seascape explorer**
  ![image](https://cloud.githubusercontent.com/assets/2837257/24107206/8986b37c-0d60-11e7-8ecd-b008af2b667c.png)

1. **What's wierd?** environmental anomalies and species affected, from [SDG14 Minutes - Google Docs](https://docs.google.com/document/d/1BPd70F3F6uT2qtV9pmYgfvno9MvNHS2XHhiZRu8HNhc/edit#):
  ![image](https://cloud.githubusercontent.com/assets/2837257/24107551/6745fb28-0d61-11e7-9e73-a30661acb4c7.png)

**Comment by bbest** [comment]
With Collin & Anni,

Where are the microbes? In lon, lat, depth, time. So approach from a different angle.

+ Microbes: publish, extract to MBON in Box, so not duplicative to NCBI + OBIS. Perhaps just publish NCBI, and OBIS harvests.

**Comment by 7yl4r** [comment]
I started pulling some information about the users from what I remember in the meeting I sat in on into [gdrive:mbon-sdg14/product-design/Global-infographics](https://docs.google.com/a/mail.usf.edu/document/d/1mxcPpjxFjzBfXzu38ZmMAPtTliAhTxE_T93PSZIclQ0/edit?usp=sharing) for (1) above . Although I'd like to help more I feel that I personally don't have a good enough understanding of the users and their needs to push through to a use-case or wireframe.

**Comment by 7yl4r** [comment]
I also tried out Pencil very briefly and didn't love it. If you haven't tried it before: draw.io integrates fairly well with google docs and has served me well in the past.
